export const strings = {
  recommended: 'Recommended For You',
  trending: 'Trending',
  featured: 'Featured',
  watchTrailer: 'Watch Trailer',
  popularShows: 'Popular show airing tonight',
  privacyPolicy: 'Privacy Policy',
  tos: 'Terms of Use',
  cookiePolicy: 'Cookie Policy',
  viewAll: 'View All',
  blog: 'Blog',
  home: 'Home',
  tm: '© 2020 TV Database. All Rights Reserved',
  menuItemTitle: 'Main Menu Item #1',
  menuItemDescription: 'Short menu description',
};
