export * from './header/header.component';
export * from './carrousel/item/carrousel-item.component';
export * from './footer/footer.component';
export * from './navbar';
export * from './carrousel/container/carrousel-container.component';
export * from './common/pager/pager.component';
export * from './common/pager-button/pager-button.component';
export * from './product-modal/product-modal.component';
export * from './slider/container/slider-container.component';
