name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Build Site
      run: |
        yarn 
        yarn next build && yarn next export -o dist

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
