name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.2

  # cypress-run:
  #   runs-on: ubuntu-16.04
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: cypress-io/github-action@v1
  #       with:
  #         browser: chrome
  #         headless: true
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Site
        run: |
          yarn 
          yarn build-storybook

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages
          FOLDER: .storybookout
